export const REFRESH_PRODUCTS = "REFRESH LANG";
export const SET_FILTER_CATEGORY1 = "SET_FILTER_CATEGORY1";
export const SET_FILTER_CATEGORY2 = "SET_FILTER_CATEGORY2";
export const SET_FILTER_SORT = "SET_FILTER_SORT";
export const SET_FILTER_BRAND = "SET_FILTER_BRAND";
export const SET_FILTER_MIN_PRICE = "SET_FILTER_MIN_PRICE";
export const SET_FILTER_MAX_PRICE = "SET_FILTER_MAX_PRICE";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";

export const SET_REGISTRATION_NAME_INPUT = "SET_REGISTRATION_NAME";
export const SET_REGISTRATION_EMAIL_INPUT = "SET_REGISTRATION_EMAIL";
export const SET_REGISTRATION_PHONE_INPUT = "SET_REGISTRATION_PHONE";
export const SET_REGISTRATION_PASSWORD_INPUT = "SET_REGISTRATION_PASSWORD";
export const SET_REGISTRATION_PASSWORD_CONFIRMED_INPUT = "SET_REGISTRATION_PASSWORD_CONFIRMED";


export const MAX_PRICE_SORT_OPTION = "MAX_PRICE_SORT_OPTION";
export const MIN_PRICE_SORT_OPTION = "MIN_PRICE_SORT_OPTION";

export const UPLOAD_CATEGORIES_AND_BRANDS = "UPLOAD_CATEGORIES_AND_BRANDS";
export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const REFRESH_PRODUCT_PAGE = "REFRESH_PRODUCT_PAGE";

export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";

export const DOMAIN = "https://localhost:5005/";
export const PRODUCTS_CONTROLLER_NAME = "CostumersProductApi/";









