export const REFRESH_PRODUCTS = "REFRESH LANG";
export const SET_FILTER_CATEGORY1 = "SET_FILTER_CATEGORY1";
export const SET_FILTER_CATEGORY2 = "SET_FILTER_CATEGORY2";
export const SET_FILTER_SORT = "SET_FILTER_SORT";
export const SET_FILTER_BRAND = "SET_FILTER_BRAND";
export const SET_FILTER_MIN_PRICE = "SET_FILTER_MIN_PRICE";
export const SET_FILTER_MAX_PRICE = "SET_FILTER_MAX_PRICE";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";

export const SET_REGISTRATION_NAME_INPUT = "SET_REGISTRATION_NAME";
export const SET_REGISTRATION_EMAIL_INPUT = "SET_REGISTRATION_EMAIL";
export const SET_REGISTRATION_PHONE_INPUT = "SET_REGISTRATION_PHONE";
export const SET_REGISTRATION_PASSWORD_INPUT = "SET_REGISTRATION_PASSWORD";
export const SET_REGISTRATION_PASSWORD_CONFIRMED_INPUT = "SET_REGISTRATION_PASSWORD_CONFIRMED";


export const MAX_PRICE_SORT_OPTION = "MAX_PRICE_SORT_OPTION";
export const MIN_PRICE_SORT_OPTION = "MIN_PRICE_SORT_OPTION";

export const UPLOAD_CATEGORIES_AND_BRANDS = "UPLOAD_CATEGORIES_AND_BRANDS";
export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const REFRESH_PRODUCT_PAGE = "REFRESH_PRODUCT_PAGE";

export const INCREMENT_PP = "INCREMENT";
export const DECREMENT_PP = "DECREMENT";

export const DOMAIN = "https://localhost:5005/";
export const PRODUCTS_CONTROLLER_NAME = "CostumersProductApi/";


//flags
export const USER_AUTH_CHANGE_STATE = "USER_AUTH_CHANGE_STATE";
export const SWITCH_LOGIN_FORM_FLAG = "SWITCH_LOGIN_FORM_FLAG";
export const SWITCH_REGISTRATION_FORM_FLAG = "SWITCH_REGISTRATION_FORM_FLAG";
export const SWITCH_BURGER_FORM_FLAG = "SWITCH_BURGER_FORM_FLAG";
export const SWITCH_THANKFULNESS_POPUP_FLAG = "SWITCH_THANKFULNESS_POPUP_FLAG";
export const SWITCH_AUTH_FORM_BACKGROUND_FLAG = "SWITCH_AUTH_FORM_BACKGROUND_FLAG";


//Auth
export const USER_REGISTRATION = "USER_REGISTRATION";
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_UPDATE = "USER_UPDATE";
export const USER_DELETE = "USER_DELETE";



export const AUTH_DOMAIN = "https://localhost:7000";








